### ISSUE TITLE
selecting rtlsdr by serial number

### ISSUE THREAD

**Issue by MrBeBo999** [wiedehopf/readsb#1]
Hi, 

I tried to let readsb select the dongle by serial number by replacing the original string by the string found by dump1090. But this did not work. I tried some variations in syntax, but no dongle found. The original string will find the rtlsdr, but not by serial number.
Do you know the right syntax?

RECEIVER_OPTIONS="--device 0 --device-type rtlsdr --gain -10 --ppm 0"                       <-- original
RECEIVER_OPTIONS="--sdr driver=rtlsdr,serial=00001090 --gain -10 --ppm 0"               <-- from dump1090

**Comment by wiedehopf** [comment]
You're using syntax used in dump978  ... it was never used in dump1090

`--device 00001090` should work.

What is the output of
```
rtl_test
```

**Comment by MrBeBo999** [comment]
Ok, thanks!

This is the output of rtl_test

Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00001090

Using device 0: Generic RTL2832U OEM
Detached kernel driver
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
[R82XX] PLL not locked!
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
Allocating 15 zero-copy buffers
lost at least 52 bytes
^CSignal caught, exiting!

User cancel, exiting...
Samples per million lost (minimum): 3
Reattached kernel driver

**Comment by wiedehopf** [comment]
So ... have you tried the correct syntax?
```
 RECEIVER_OPTIONS="--device 00001090 --device-type rtlsdr --gain -10 --ppm 0" 
```

**Comment by MrBeBo999** [comment]
Yes, it works. I have planes in tar1090, thanks! 
Now I have to do the same trick with the other dongle and rtl_tcp ;)
