### ISSUE TITLE
How use readsb on openSUSE?

### ISSUE THREAD

**Issue by vatprcyq** [wiedehopf/readsb#13]
can use readsb on openSUSE?(amd64/arm64)

**Comment by wiedehopf** [comment]
The debian package won't work, you'll have to compile yourself using make.
Dependencies are described in the readme.

You'd have to make a systemd service or whatever suse is using, check the debian folder for an example service file.
It expects a conf file /etc/default/readsb an example is available in the debian folder.

Installing tar1090, the connected webinterface is done using a shell script and uses lighttpd or nginx.
You'd have to either run and make the install script work with opensuse or follow it manually.

**Comment by vatprcyq** [comment]
BTW,how to use tar1090 with Apache?
________________________________
发件人: wiedehopf ***@***.***>
发送时间: 2022年5月20日 1:16
收件人: wiedehopf/readsb ***@***.***>
抄送: vatprcyq ***@***.***>; Author ***@***.***>
主题: Re: [wiedehopf/readsb] How use readsb on openSUSE? (Issue #13)


The debian package won't work, you'll have to compile yourself using make.
Dependencies are described in the readme.

You'd have to make a systemd service or whatever suse is using, check the debian folder for an example service file.
It expects a conf file /etc/default/readsb an example is available in the debian folder.

Installing tar1090, the connected webinterface is done using a shell script and uses lighttpd or nginx.
You'd have to either run and make the install script work with opensuse or follow it manually.

―

**Comment by wiedehopf** [comment]
Either use one of the provided options (nginx / lighttpd) or infer from those configuration files.

lighttpd is the option for default Raspbian installs, nginx is for people who want a proper webserver.
I'd recommend to just switch to nginx ... or you could run it on a port that's not 80.

**Comment by vatprcyq** [comment]
OK I‘ll try lighttpd on port 8099

________________________________
发件人: wiedehopf ***@***.***>
发送时间: 2022年5月20日 4:23
收件人: wiedehopf/readsb ***@***.***>
抄送: vatprcyq ***@***.***>; Author ***@***.***>
主题: Re: [wiedehopf/readsb] How use readsb on openSUSE? (Issue #13)


Either use one of the provided options (nginx / lighttpd) or infer from those configuration files.

lighttpd is the option for default Raspbian installs, nginx is for people who want a proper webserver.
I'd recommend to just switch to nginx ... or you could run it on a port that's not 80.

―

**Comment by wiedehopf** [comment]
It's not super complicated, read the lighttpd configuration in the repository and configure apache accordingly.

**Comment by wiedehopf** [comment]
Yeah, for using lighttpd ... it kinda needs the modifications by the install.sh script.

This would be a modified example of a lighttpd configuration file: https://pastebin.com/TV6qWUaE

**Comment by vatprcyq** [comment]
> The debian package won't work, you'll have to compile yourself using make. Dependencies are described in the readme.
> 
> You'd have to make a systemd service or whatever suse is using, check the debian folder for an example service file. It expects a conf file /etc/default/readsb an example is available in the debian folder.
> 
> Installing tar1090, the connected webinterface is done using a shell script and uses lighttpd or nginx. You'd have to either run and make the install script work with opensuse or follow it manually.

Can directly use script adsb-scripts/readsb-nopackage.sh ?

**Comment by wiedehopf** [comment]
Use debian or be competent.

Or run it in docker i suppose: https://github.com/sdr-enthusiasts/docker-tar1090

**Comment by sysblade** [comment]
I tried to compile it with OpenSuse Leap 15.3 but I get this error:

```
globe_index.c: In function ‘traceDelete’:
globe_index.c:1515:8: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     if (newLen < oldLen) {
        ^
cc1: all warnings being treated as errors
make: *** [Makefile:120: globe_index.o] Error 1
```

With `make AIRCRAFT_HASH_BITS=11 RTLSDR=yes OPTIMIZE="-O3 -march=native"`

I had to remove the `-Werror` from the makefile (not sure it's really safe?)

**Comment by wiedehopf** [comment]
It's int .... no that won't overflow.

Why do different gcc behave so differently in regards to all those checks ....
More recent gcc doesn't complain.

After some googling:
> By the way, I ran into this issue on GCC 4.7, but the same code compiled without warning using 4.8 -- perhaps indicating that the GCC developers recognized the need to be a bit less "strict" in the normal case (or maybe it was just due to differences in the optimizer).

Are you really on that old of an gcc?
Compile -O2 instead?

And do you just enjoy ancient systems or is this part of a commercial deployment, i'm curious how the software is being used :)


-----

Added some checks for that stupid ancient compiler so it hopefully stops complaining, please:
```
git clone --depth 1 sid https://github.com/wiedehopf/readsb.git
```

And try if that compiles

**Comment by sysblade** [comment]
This is my current version 
```
❯ gcc --version
gcc (SUSE Linux) 7.5.0
```

openSUSE leap 15.3 is from June 2021, not that old :)

On your `sid` branch I don't get this error anymore

**Comment by wiedehopf** [comment]
#fixed-by: aa13e7966befbfbd04471578e7277cb35eb78b7f

**Comment by wiedehopf** [comment]
Removing -Werror is perfectly safe.
The compiler won't save you from most of the mistakes i make.

Running readsb is perfectly unsafe.
While i try and not make mistakes, they happen somewhat frequently.

**Comment by sysblade** [comment]
Thanks for the quick reply.
I'm just not too familiar with gcc, C in general and the issue that can happens because of that (had seen too many segfaults in my life)

**Comment by wiedehopf** [comment]
As i said, i make mistakes, expect plenty of segfaults :)

Running pretty good though right now.
And the track record hasn't been too horrible i think.

Anyhow segfaults are of course something i'll try and fix as quickly as possible if i see them myself or get a bug report.
There are easy and hard ones to find the root cause obviously.

**Comment by sysblade** [comment]
Oh I was not talking about segfaults in readsb (I didn't had any) but in general.

**Comment by wiedehopf** [comment]
One last thing, don't use the sid branch, it's a testing branch.

**Comment by vatprcyq** [comment]
> 

BTW  in openSUSE it's Tumbleweed version
Label is a ∞ same as symbol on Luo Tianyi's head

**Comment by vatprcyq** [comment]
> This is my current version
> 
> ```
> ❯ gcc --version
> gcc (SUSE Linux) 7.5.0
> ```
> 
> openSUSE leap 15.3 is from June 2021, not that old :)
> 
> On your `sid` branch I don't get this error anymore

My gcc version:
gcc --version
gcc (SUSE Linux) 12.1.0
Copyright © 2022 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。

**Comment by wiedehopf** [comment]
Did you get it working now?

The readsb-install.sh should be easier for you to change now as it's no longer building the debian package.
https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb

You'll still have to modify it / install the software required with yum.

**Comment by vatprcyq** [comment]
OK will try it.
BTW... software management command in openSUSE is zypper
________________________________
发件人: wiedehopf ***@***.***>
发送时间: 2022年7月4日 22:50
收件人: wiedehopf/readsb ***@***.***>
抄送: vatprcyq ***@***.***>; Author ***@***.***>
主题: Re: [wiedehopf/readsb] How use readsb on openSUSE? (Issue #13)


Did you get it working now?

The readsb-install.sh should be easier for you to change now as it's no longer building the debian package.
https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb

You'll still have to modify it / install the software required with yum.

―
