### ISSUE TITLE
readsb and beast receiver

### ISSUE THREAD

**Issue by RecepAGulec** [wiedehopf/readsb#16]
Hi,
Can I use a Jetvision Mode-s beast receiver with readsb?
73s

**Comment by wiedehopf** [comment]
check readsb --help

(yes you can)

See this page for other useful ADS-B stuff: https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite:-ADS-B-receiver

**Comment by RecepAGulec** [comment]
It's done. Thank you very much.
