### ISSUE TITLE
Error in line 101 (readsb-install.sh)

### ISSUE THREAD

**Issue by MichaK99** [wiedehopf/readsb#19]
Hi,
yesterday I tried to compile readsb on my proxmox VM under Debian (readsb-install.sh).
I always get an error MSG: Error in line 101 : `make "-j${THREADS}" AIRCRAFT_HASH_BITS=16 RTLSDR=yes OPTIMIZE="-O3 -march=native" "$@"`

I did it before also under my VM and had to problems at all.

**Comment by wiedehopf** [comment]
Post the actual error which will be above what you posted?
