### ISSUE TITLE
Update piaware package

### ISSUE THREAD

**Issue by nar1117** [wiedehopf/readsb#20]
Hello all,

I built my feeder a while ago and haven't touched it since. The Piaware feeder specifically is very finicky and as of late it has been crashing. The only way I know is that I get the "your feeder is offline" email from FlightAware.

Quick google search shows that others have had issues with PiAware working consistently, so I'm wondering if it will break anything set up by the readsb-install if I update that package manually using apt.

Specifically, these are the relevant updates available from running "apt update":

`piaware-repository/unknown 7.2~bpo10+1 all [upgradable from: 6.1]
piaware/unknown 7.2~bpo10+1 armhf [upgradable from: 7.1~bpo10+1]`

Thoughts?

Edit: I should clarify that I did update the readsb installation using the script. However, the piaware feeder was not updated during that process. When that feeder crashes, it gets stuck at 100% CPU usage and only a reboot fixes it.

**Comment by wiedehopf** [comment]
bpo means you're on some old Raspbian version. Might want a new image at some point.

Anyhow apt dist-upgrade usually doesn't cause any issues.
Rerunning the readsb install script fixes most issues .... in case there should be any.
