### ISSUE TITLE
Separate session of readsb to only import api

### ISSUE THREAD

**Issue by ggoodloff** [wiedehopf/readsb#27]
I want to run a separate session of tar1090 and readsb that only reads FROM an JSON file from https://api.adsb.lol/v2/all

This is to be updated every 30-60 seconds and I would like the data (and possibly tracks) to show on tar1090.

Is this possible? All the reading I can find relates to connecting back to a beast port. This caused me a data loop.  

I'm only looking to take a snapshot (as a bot) based on data in the API.

Thanks

**Comment by wiedehopf** [comment]
Beyond the scope of this project.
