### ISSUE TITLE
Is it possible:   --min-range=<dist>  like  --max-range=<dist>  

### ISSUE THREAD

**Issue by madjuju** [wiedehopf/readsb#53]
Is it possible to set a min Range ?

ex. Just want readsb bypass all plane who are from 0 to 50 nmi from me ?

**Comment by wiedehopf** [comment]
I'm not implementing features, handling this project as bug fix and some PRs.

**Comment by NoseyNick** [comment]
Oh interesting! Is there a newer / better / faster / stronger / more maintained / feature-full fork we are all supposed to have become aware of?
