### ISSUE TITLE
Feature Request: preserve outlines.json after restart

### ISSUE THREAD

**Issue by dxmekch** [wiedehopf/readsb#60]
Hello:)

I wonder if it's possible to implement an option (e.g. `--range-outline-preserve=`) to retain the outlines.json (similar to 
 `--write-state=`) after a restart of readsb or the device. This would probably make a helpful addition to the existing option 
 `--range-outline-hours=` and would prevent that the outlines are reset after a power loss or restart of the device (e.g. to apply updates).

**Comment by wiedehopf** [comment]
write-state already preserves the outline.

**Comment by dxmekch** [comment]
I just restarted my readsb and it appears that the traces are saved but the outline is definitely not.

**Comment by wiedehopf** [comment]
Please restart the service again and provide me with logs from startup to exit.

**Comment by dxmekch** [comment]
I guess I figured it out, it seems like we can't point to the same dir as --write-json, `/run/readsb` in my case, for state storage, this dir seems not to be persistent.

`..... first start with state enabled / directory not backed by persistent storage`

I now changed the dir and it's working.

`Mar 20 17:48:33 pi3 readsb[27288]: loading state .....`
`Mar 20 17:48:33 pi3 readsb[27288]: actual range outline, read bytes: 368644`
`Mar 20 17:48:33 pi3 readsb[27288]:  .......... done, loaded 44 aircraft in 0.018 seconds!`
