### ISSUE TITLE
A reference to application in the readme

### ISSUE THREAD

**Issue by alexey-milovidov** [wiedehopf/readsb#65]
The readme currently lists one example application here: https://github.com/wiedehopf/readsb?tab=readme-ov-file#global-map-of-aircraft

Recently, I've created a rich visualization tool based on the output of readsb: https://adsb.exposed
The source code, along with the data preparation scripts, is located here: https://github.com/ClickHouse/adsb.exposed/

I would appreciate it if there would be a place to put a reference to it!

**Comment by NoseyNick** [comment]
**WOW** That app is gorgeous! :star_struck:
Produces works of art from real-world data, love it!   :heart_eyes:
