### ISSUE TITLE
[nnn blob data] messages, how to investigate ?

### ISSUE THREAD

**Issue by olyair11** [wiedehopf/readsb#68]
I have created an application that sends SBS TCP JAERO messages. Although most of the time cooperation with readsb is fine,
sometimes the below message worries me that I send invalid SBS messages, or ?
Could not find where these messages are coming from.
Please show me how to dump the blob data in order to fix my application. TIA

Apr 23 04:09:10 cld67.example.net systemd[1]: Started readsb ADS-B receiver.
Apr 23 04:09:11 cld67.example.net readsb[25593]: invoked by: /usr/local/bin/readsb --fix --debug=nGRUXO --quiet --net-only --net-heartbeat 60 --net-ingest --net-receiver-id --heatmap-dir /usr/local/share/tar1090/html/globe_history --heatmap 30 --net-sbs-jaero-in-port=33303 --write-receiver-id-json --jaero-timeout 10 --write-json /run/readsb --json-location-accuracy 1 --db-file /usr/local/share/tar1090/aircraft.csv.gz --db-file-lt
Apr 23 04:09:11 cld67.example.net readsb[25593]: [2024-04-23 04:09:11.000 EEST] readsb starting up.
Apr 23 04:09:11 cld67.example.net readsb[25593]: readsb version: 3.14.1618 compiled on 2024-04-22, 02:14:51 (EET)
Apr 23 04:09:11 cld67.example.net readsb[25593]: 33303: SBS TCP input JAERO port
Apr 23 04:09:11 cld67.example.net readsb[25593]: Database update in progress!
Apr 23 04:09:11 cld67.example.net readsb[25593]: Database update first part took 0.561 seconds!
Apr 23 04:09:12 cld67.example.net readsb[25593]: Database update done! (critical part took 0.002 seconds)
Apr 23 04:09:51 cld67.example.net readsb[25593]: SBS TCP input JAERO connection count: 1
Apr 23 04:18:53 cld67.example.net readsb[25593]: new client:                        rId 47d664bc-2886-417c-0000-000000000000 host(127.0.0.1), port(51716)
Apr 23 05:41:01 cld67.example.net readsb[25593]: [285B blob data]
Apr 23 05:41:10 cld67.example.net readsb[25593]: [285B blob data]
Apr 23 05:41:38 cld67.example.net readsb[25593]: [284B blob data]
Apr 23 05:42:36 cld67.example.net readsb[25593]: [283B blob data]
Apr 23 05:42:36 cld67.example.net readsb[25593]: [283B blob data]
Apr 23 05:42:42 cld67.example.net readsb[25593]: [284B blob data]
Apr 23 05:43:46 cld67.example.net readsb[25593]: [283B blob data]
Apr 23 05:46:59 cld67.example.net readsb[25593]: [282B blob data]
Apr 23 05:48:03 cld67.example.net readsb[25593]: [282B blob data]
Apr 23 05:48:23 cld67.example.net readsb[25593]: [282B blob data]
Apr 23 05:48:27 cld67.example.net readsb[25593]: [282B blob data]
Apr 23 05:49:07 cld67.example.net readsb[25593]: [284B blob data]
Apr 23 05:50:11 cld67.example.net readsb[25593]: [282B blob data]
Apr 23 05:50:12 cld67.example.net readsb[25593]: [277B blob data]

**Comment by wiedehopf** [comment]
Add --no-pager to journalctl and you'll get the actual offending messages.

You can also pipe it to cat -A to display all characters in more obvious ways (newlines etc)

**Comment by olyair11** [comment]
Thanks for coming back so quickly.
I tried both but no blob contents showed up.
"journalctl -a ..." did the trick, blob data are included.
Regards
