### ISSUE TITLE
FEATURE REQUEST: Prompts

### ISSUE THREAD

**Issue by mihanson** [wiedehopf/readsb#71]
It would be nice if the script prompted the user for SDR serial or index number and latitude/longitude when installing. It may also be helpful to remind the user to restart collectd for graphs1090 to work again.
![dump1090-localhost-local_trailing_rate-2h](https://github.com/wiedehopf/readsb/assets/45887360/fd7abb54-6bbc-4c33-a0c5-417b88738c2e)

**Comment by wiedehopf** [comment]
The script isn't part of this repo.

The readsb install script readme has clear instructions on how to set the location / edit the config.

**Comment by mihanson** [comment]
I know the readme has that info, but I thought it would be nice to enter it while installing. I understand that you do not want to implement.
