### ISSUE TITLE
graphs1090 not updating after readsb install script ran

### ISSUE THREAD

**Issue by ehurrn** [wiedehopf/readsb#8]
Quick and dirty console output: https://pastebin.com/LRc3WBw4

The issue appears to be collectd is looking for /usr/share/graphs1090/data-symlink/data/stats.json and /usr/share/graphs1090/data-symlink/data/ is a symlink to /run/dump1090-fa which doesn't exist anymore.

**Comment by wiedehopf** [comment]
rerun graphs1090 install for it to autodetect changed data source.

**Comment by ehurrn** [comment]
Thanks!
